### ISSUE TITLE
Unpredictable?

### ISSUE THREAD

**Issue by ghost** [WereCatf/PCF8574_ESP#2]
I tried your example and wrote one of my own with a NodeMCU. Outputs can be controlled reliably, but forcing an interrupt via a PB to toggle or write to LED is super unpredictable.  I tried all the options, but FALLING is the one that I would use. Not sure why you setup the attachInterrupt with CHANGE, but FALLING seems to "work" the same as CHANGE or even LOW. Any ideas?

**Comment by WereCatf** [comment]
I used CHANGE just so that when the button goes HIGH the LED goes HIGH and when the button goes LOW the LED goes LOW. If you only trigger the interrupt on FALLING then the LED would go LOW, but never back to HIGH, unless you modified the code to require multiple button-presses or pull the LED back HIGH after a certain amount of time has passed. If you want to do it that way then go ahead, it's just a matter of how you like it.

**Comment by ghost** [comment]
Ok thanks. But I still don't understand the unpredictable operation. Many times the LED doesn't fire or will stay on (seemingly locked up)... and other times will go off on its own. I will do some more testing and let you know.

**Comment by WereCatf** [comment]
The simple example was never meant to be a full, totally predictable and reliable solution, like e.g. there is no debounce for the push-button at all -- its sole purpose was to provide a quick example of how to use the library and make it do something.

Your problem sounds like something that would be caused by not having any debounce-circuit or -code, and there are plenty of resources on that all around the web, and of course, only triggering on FALLING-edge, but requiring more button-presses is another way of increasing the reliability.
